version: "3.6"
services:
  espcam-secserver:
    image: techblog/espcam-secserver
    container_name: espcam-secserver
    restart: always
    environment:
      - GREEN_API_INSTANCE_ID= #Green API Instance Id
      - GREEN_API_TOKEN= #Green API Token
      - TARGET= #Target phone number 972*********@c.us for contact or @g.us for group
      - MESSAGE= #Caption for the image sent
    ports:
      - "80:80"